volumes:
    db_data:
    uploads_data:

networks:
    dokploy-network:
        external: true

services:
    app:
        build: .
        networks:
            - dokploy-network
        env_file:
            # Copy from ./server/.env.example
            - ./.env
        volumes:
            - db_data:/app/server/data
            - uploads_data:/app/server/uploads
        restart: unless-stopped
